---
title: "individual1"
author: "Connor Toliver"
date: "3/21/2020"
output: html_document
---

```{r}
library(readxl)
defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offense <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
biography <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
```

```{r}
library(dplyr)
library(tidyverse)

defense$Name <- factor(defense$Name)
defense$Opponent_Opponent <- factor(defense$Opponent_Opponent)

offense$Name <- factor(offense$Name)
offense$Opponent_Opponent <- factor(offense$Opponent_Opponent)
biography$Name <- factor(biography$Name)
```

```{r}
library(readxl)
library(tidyverse)
defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offense <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
biography <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
```

```{r}
defClean <- defense %>% 
  mutate_at(c('Name', 'Opponent_Opponent'), factor)

offClean <- offense %>% 
  mutate_at(c('Name', 'Opponent_Opponent'), factor)

bioClean <- biography %>% 
  mutate_at(c('Name', 'Hometown', 'Highschool', 'Position', 'Class'), factor)
```

```{r}
defClean <- defClean %>% 
  mutate_at(c(3:11), as.numeric)

offClean <- offClean %>% 
  mutate_at(c(3:12), as.numeric)

bioClean <- bioClean %>% 
  mutate(temp1 = as.numeric(substring(Height, 1, 1))) %>% 
  mutate(temp2 = as.numeric(substring(Height, 3))) %>% 
  mutate(Height = (temp1 * 12) + temp2) %>% 
  mutate(temp1 = NULL) %>% 
  mutate(temp2 = NULL)

str(bioClean)
```

```{r}
str(defClean)
```

```{r}
str(offClean)
```

```{r}
str(bioClean)
```


```{r}
defClean <- defClean %>% 
  pivot_longer(Tackles_Solo:Pass_PB, names_to = 'Statistic')

ggplot(defClean, aes(x = value)) + geom_histogram() + facet_wrap(~Statistic)
```


```{r}
defClean %>% 
  filter(Opponent_Opponent == 'West Virginia' | Opponent_Opponent == 'Kansas State') %>% 
  filter(Statistic == 'Tackles_Solo') %>% 
  pivot_wider(names_from = 'Opponent_Opponent', values_from = 'value') %>% 
  select(Name, 'West Virginia', 'Kansas State') %>% 
  ggplot(aes(`West Virginia`, `Kansas State`)) + geom_jitter()
```

```{r}
bioClean <- bioClean %>% 
  separate(Hometown, sep=', ', into=c('City', 'State'))

bioClean %>% 
  group_by(State) %>% 
  select(State) %>% 
  summarize(n =n())
```

